question_data = [
    {"category": "General Knowledge",
     "type": "multiple",
     "difficulty": "medium",
     "question": "What is the world&#039;s most expensive spice by weight?",
     "correct_answer": "Saffron",
     "incorrect_answers": ["Cinnamon", "Cardamom", "Vanilla"]},
    {"category": "General Knowledge",
     "type": "multiple",
     "difficulty": "medium",
     "question": "What does a milliner make and sell?",
     "correct_answer": "Hats",
     "incorrect_answers": ["Shoes", "Belts", "Shirts"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "Which river flows through the Scottish city of Glasgow?", "correct_answer": "Clyde",
     "incorrect_answers": ["Tay", "Dee", "Tweed"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "Rolex is a company that specializes in what type of product?", "correct_answer": "Watches",
     "incorrect_answers": ["Cars", "Computers", "Sports equipment"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Gumbo is a stew that originated in Louisiana.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "French is an official language in Canada.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge",
     "type": "multiple",
     "difficulty": "easy",
     "question": "Which American president appears on a one dollar bill?",
     "correct_answer": "George Washington",
     "incorrect_answers": ["Thomas Jefferson",
                           "Abraham Lincoln", "Benjamin Franklin"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "Which language is NOT Indo-European?", "correct_answer": "Hungarian",
     "incorrect_answers": ["Russian", "Greek", "Latvian"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "The words &quot;bungalow&quot; and &quot;shampoo&quot; originate from the languages of which country?",
     "correct_answer": "India", "incorrect_answers": ["Papua New Guinea", "Ethiopia", "China"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The word &quot;news&quot; originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "After how many years would you celebrate your crystal anniversary?", "correct_answer": "15",
     "incorrect_answers": ["20", "10", "25"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Bulls are attracted to the color red.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "Which of the following is an existing family in &quot;The Sims&quot;?",
     "correct_answer": "The Goth Family",
     "incorrect_answers": ["The Family", "The Simoleon Family", "The Proud Family"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "What is the name given to Indian food cooked over charcoal in a clay oven?",
     "correct_answer": "Tandoori", "incorrect_answers": ["Biryani", "Pani puri", "Tiki masala"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which of these colours is NOT featured in the logo for Google?", "correct_answer": "Pink",
     "incorrect_answers": ["Yellow", "Blue", "Green"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is the Spanish word for &quot;donkey&quot;?", "correct_answer": "Burro",
     "incorrect_answers": ["Caballo", "Toro", "Perro"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "What is the romanized Chinese word for &quot;airplane&quot;?", "correct_answer": "Feiji",
     "incorrect_answers": ["Qiche", "Zongxian", "Huojian"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "Which musician has collaborated with American producer Porter Robinson and released the 2016 song &quot;Shelter&quot;?",
     "correct_answer": "Madeon", "incorrect_answers": ["Mat Zo", "deadmau5", "Zedd"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "The Swedish word &quot;Grunka&quot; means what in English?", "correct_answer": "Thing",
     "incorrect_answers": ["People", "Place", "Pineapple"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "Who is the founder of &quot;The Lego Group&quot;?", "correct_answer": "Ole Kirk Christiansen",
     "incorrect_answers": [" Jens Niels Christiansen", "Kirstine Christiansen", " Gerhardt Kirk Christiansen"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The French word for &quot;glass&quot; is &quot;glace&quot;.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
     "question": "In Scandinavian languages, the letter &Aring; means river.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "De Eemhof, Port Zelande and Het Heijderbos are holiday villas owned by what company?",
     "correct_answer": "Center Parcs", "incorrect_answers": ["Yelloh Village", "Keycamp", "Villa Plus"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "What does the Latin phrase &quot;Veni, vidi, vici&quot; translate into English?",
     "correct_answer": "I came, I saw, I conquered",
     "incorrect_answers": ["See no evil, hear no evil, speak no evil", "Life, liberty, and happiness",
                           "Past, present, and future"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
     "question": "Stagecoach owned &quot;South West Trains&quot; before losing the rights to FirstGroup and MTR in March of 2017.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "Who invented Pastafarianism?", "correct_answer": "Bobby Henderson",
     "incorrect_answers": ["Eric Tignor", "Bill Nye", "Zach Soldi"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "Which slogan did the fast food company, McDonald&#039;s, use before their &quot;I&#039;m Lovin&#039; It&quot; slogan?",
     "correct_answer": "We Love to See You Smile",
     "incorrect_answers": ["Why Pay More!?", "Have It Your Way", "Making People Happy Through Food"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which sign of the zodiac comes between Virgo and Scorpio?", "correct_answer": "Libra",
     "incorrect_answers": ["Gemini", "Taurus", "Capricorn"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which of the following presidents is not on Mount Rushmore?", "correct_answer": "John F. Kennedy",
     "incorrect_answers": ["Theodore Roosevelt", "Abraham Lincoln", "Thomas Jefferson"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "If someone said &quot;you are olid&quot;, what would they mean?",
     "correct_answer": "You smell extremely unpleasant.",
     "incorrect_answers": ["You are out of shape\/weak.", "Your appearance is repulsive.",
                           "You are incomprehensible\/an idiot."]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "Where did the pineapple plant originate?", "correct_answer": "South America",
     "incorrect_answers": ["Hawaii", "Europe", "Asia"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The National Animal of Scotland is the Unicorn.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The British organisation CAMRA stands for The Campaign for Real Ale.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "If you are caught &quot;Goldbricking&quot;, what are you doing wrong?",
     "correct_answer": "Slacking",
     "incorrect_answers": ["Smoking", "Stealing", "Cheating"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "A statue of Charles Darwin sits in what London museum?",
     "correct_answer": "Natural History Museum",
     "incorrect_answers": ["Tate", "British Museum", "Science Museum"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "What is the highest number of Michelin stars a restaurant can receive?",
     "correct_answer": "Three",
     "incorrect_answers": ["Four", "Five", "Six"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "The Flag of the European Union has how many stars on it?", "correct_answer": "12",
     "incorrect_answers": ["10", "14", "16"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "How many notes are there on a standard grand piano?", "correct_answer": "88",
     "incorrect_answers": ["98", "108", "78"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "How many furlongs are there in a mile?", "correct_answer": "Eight",
     "incorrect_answers": ["Two", "Four", "Six"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "In the MMO RPG &quot;Realm of the Mad God&quot;, what dungeon is widely considered to be the most difficult?",
     "correct_answer": "The Shatter&#039;s",
     "incorrect_answers": ["Snake Pit", "The Tomb of the Acient&#039;s", "The Puppet Master&#039;s Theater"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is the name of NASA&rsquo;s most famous space telescope?",
     "correct_answer": "Hubble Space Telescope",
     "incorrect_answers": ["Big Eye", "Death Star", "Millenium Falcon"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "Which of these cities does NOT have a United States Minting location?",
     "correct_answer": "St. Louis, MO",
     "incorrect_answers": ["San Fransisco, CA", "Philidelphia, PA", "West Point, NY"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Who is the author of Jurrasic Park?", "correct_answer": "Michael Crichton",
     "incorrect_answers": ["Peter Benchley", "Chuck Paluhniuk", "Irvine Welsh"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "Linus Pauling, one of the only winners of multiple Nobel Prizes, earned his Nobel Prizes in Chemistry and what?",
     "correct_answer": "Peace", "incorrect_answers": ["Physics", "Economics", "Physiology\/Medicine"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "When was the Playstation 3 released?", "correct_answer": "November 11, 2006",
     "incorrect_answers": ["January 8, 2007", "December 25, 2007", "July 16, 2006"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
     "question": "NCIS stands for &quot;Navy Corps Investigative Service&quot;", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which of these Marvel games was released on the Playstation 2?",
     "correct_answer": "Spider-Man 2",
     "incorrect_answers": ["Silver Surfer", "Howard the Duck",
                           "Wolverine: Adamantium Rage"]}]
